<../../mkconfig

TARG=\
	ssh.dis\
	sftpfs.dis\
	dsagen.dis\
	decenc.dis\

MODULES=\
	sftp.m\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyring.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
