<../../mkconfig

DIRS=\
	auth\

TARG=\
	ssh.dis\
	sftpfs.dis\
	decenc.dis\
	sshpubkey.dis\

MODULES=\
	sftp.m\
	../lib/sshfmt.m\
	../lib/sshlib.m\

SYSMODULES=\
	arg.m\
	attrdb.m\
	bufio.m\
	daytime.m\
	draw.m\
	encoding.m\
	keyring.m\
	security.m\
	string.m\
	styx.m\
	sys.m\
	tables.m\
	util0.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
